name: pyrestus
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.*
  - pandas=1.3.*
  - tqdm=4.*
  - pillow=8.4.*
  - scipy=1.7.*
  - cython=0.29.*
  - pydicom=2.2.*
  - opencv=4.5.*
  - numba
